# 1장 소개

## 1.4 필수 라이브러리 모듈들
### 1.4.3 SciPy

In [2]:
import numpy as np
from scipy import sparse

# np.eye : 대각선 원소는 1이고 나머지는 0인 2차원 NumPy 배열을 만든다.
eye = np.eye(4)
print('NumPy 배열:\n',eye)

NumPy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# NumPy 배열을 CSR 포맷의 SciPy 희박 행렬로 변환합니다.
# 0이 아닌 원소만 저장됩니다.